core/urls.py
from django.shortcuts import redirect
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', auth_views.LoginView.as_view(template_name= 'user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name= 'user/logout.html'), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.http import HttpResponse
from django.shortcuts import render
from projects.models import Project, Task
from user.models import User, UserProfile

# Create your views here.

def index(request):
    return render(request, 'core/index.html')

def dashboard(request):
    res = {}
    projects = Project.objects.all().count()
    task = Task.objects.all().count()
    active_proeject = Project.objects.filter(status__in = ["2", "3"]).count()
    res["project"] = projects
    res["task"] = task
    res["active_proeject"] = active_proeject
    # print(active_proeject)
    # print(res)
    return render(request, "core/dashboard.html", context=res)

def context(request): # send context to base.html
    # if not request.session.session_key:
    #     request.session.create()
    users = User.objects.all()
    users_prof = UserProfile.objects.all()
    if request.user.is_authenticated:
        try:
            users_prof = UserProfile.objects.exclude(
                id=request.user.userprofile_set.values_list()[0][0])  # exclude himself from invite list
            user_id = request.user.userprofile_set.values_list()[0][0]
            logged_user = UserProfile.objects.get(id=user_id)
            context = {
                'users': users,
                'users_prof': users_prof,
                'logged_user': logged_user,
            }
            return context
        except:
            users_prof = UserProfile.objects.all()
            context = {
                'users':users,
                'users_prof':users_prof,
            }
            return context
    else:
        context = {
            'users': users,
            'users_prof': users_prof,
        }
        return context
    

core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-147225311-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-147225311-2');
    </script>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="CoreUI - Open Source Bootstrap Admin Template">
  <meta name="author" content="Smit-Panchal">
  <meta name="keyword" content="Bootstrap,Admin,Template,Open,Source,AngularJS,Angular,Angular2,Angular 2,Angular4,Angular 4,jQuery,CSS,HTML,RWD,Dashboard,React,React.js,Vue,Vue.js">
  <meta name="google-site-verification" content="83fcqoPn-YTkXathQiicW-x3U2RWZh4PaPUzk91wtjY" />
  
  <title>Project Manager {% block title%} {% endblock %}</title>

  <!-- Icons -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.9/css/all.css" integrity="sha384-5SOiIsAziJl6AWe0HWRKTXlfcSHKmYV4RBF18PPJ173Kzn7jzMyFuTtk8JA7QQG1" crossorigin="anonymous">
  <link href="{% static 'core/css/simple-line-icons.min.css' %}" rel="stylesheet">

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!-- Main styles for this application -->
  <link href="{% static 'core/css/estilo.css' %}" rel="stylesheet">
  <link href="{% static 'core/css/style.css' %}" rel="stylesheet">

<style>
    /* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  padding-top: 100px; /* Location of the box */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content */
.modal-content {
  background-color: #fefefe;
  margin: auto;
  padding: 20px;
  border: 1px solid #888;
  width: 80%;
}

/* The Close Button */
.close {
  color: #aaaaaa;
  float: right;
  font-size: 28px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: #000;
  text-decoration: none;
  cursor: pointer;
}
</style>

</head>
{% block body %}
<body class="app header-fixed sidebar-fixed aside-menu-fixed aside-menu-hidden">

  <header class="app-header navbar">
    <button class="navbar-toggler mobile-sidebar-toggler d-lg-none mr-auto" type="button">
      <span class="navbar-toggler-icon"></span>
    </button>
    <img src="{% static 'core/img/logos/vor.png' %}" alt="" class="brand-gui ml-2 d-none d-sm-block p-2">
    <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- ----------------------------------------- Modal content -------------------------------------->
    <!-- Trigger/Open The Modal -->
{% comment %} <button id="myBtn">Open Modal</button> {% endcomment %}

<!-- The Modal -->
<div id="myModal" class="modal">

  <!-- Modal content -->
  <div class="modal-content">
    <span class="close">&times;</span>
    <p>It's lunch time..</p>
  </div>

</div>



<!-- ----------------------------------------- Modal content -------------------------------------->


    <ul class="nav navbar-nav d-md-down-none">
      <li class="nav-item px-3">
        <a class="nav-link" href="{% url 'core:index' %}">Home</a>
      </li>
      <li class="nav-item px-3">
        <a class="nav-link" href="{% url 'core:dashboard' %}">Dashboard</a>
      </li>
    </ul>
    <ul class="nav navbar-nav ml-auto">
      <li class="nav-item d-md-down-none">
        <a class="nav-link" href="#"><i class="fa fa-bell"></i><span class="badge badge-pill badge-danger">{{ logged_user.received_invites.count }}</span></a>
      </li>
      <li class="nav-item d-md-down-none">
        <a class="nav-link" href="#"><i class="fa fa-list"></i></a>
      </li>
      {% if user.is_authenticated %}
      <li class="text-muted">Hello, {{ user.first_name }}</li>
      {% else %}
      <li class="text-muted">
        <a href="#">sign in</a>
      </li>
      {% endif %}
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
          {% if user.is_authenticated %}
          <img src="{{ logged_user.img.url }}" class="img-avatar" alt="{{ user }}">
          {% else %}
          <img src="{% static 'core/img/avatar/blank_profile.png' %}" class="img-avatar" alt="{{ user }}">
          {% endif %}
        </a>

        <div class="dropdown-menu dropdown-menu-right">
          <div class="dropdown-header text-center">
            <strong>Account</strong>
        </div>
        {% if user.is_authenticated %}
        <a class="dropdown-item" href="{% url 'user:profile' %}"><i class="fa fa-user"></i> Profile</a>
          <!--<a class="dropdown-item" href="#"><i class="fa fa-file"></i> Projects<span class="badge badge-primary">42</span></a>-->
        <div class="divider"></div>

        <a class="dropdown-item" href="{% url 'core:logout' %}"><i class="fa fa-lock"></i> Logout</a>
        {% else %}
        <a class="dropdown-item" href="{% url 'core:login' %}"><i class="fa fa-user"></i> Login</a>
        {% endif %}
      </div>

      </li>
    </ul>

  </header>

  <div class="app-body">
    <div class="sidebar">
      <nav class="sidebar-nav">
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:index' %}"><i class="fa fa-home"></i> Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:dashboard' %}"><i class="fa fa-tachometer-alt"></i> Dashboard</a>
          </li>

          <li class="nav-item nav-dropdown">
            <a class="nav-link nav-dropdown-toggle" href="#"><i class="fa fa-tachometer-alt"></i> Views</a>
            <ul class="nav-dropdown-items">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'views:project-view' %}"><i class="fa fa-paper-plane ml-2"></i> All Projects</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'views:users-view' %}"><i class="fa fa-user ml-2"></i> Mine</a>
              </li>
            </ul>
          </li>

          
          <li class="nav-item nav-dropdown">
            <a class="nav-link nav-dropdown-toggle" href="{% url 'projects:project' %}"><i class="fa fa-puzzle-piece"></i> Projects</a>
            <ul class="nav-dropdown-items">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'projects:create-project' %}"><i class="fa fa-plus ml-2"></i> New Project</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'projects:create-task' %}"><i class="fa fa-plus ml-2"></i> New Task</a>
              </li>
            </ul>
          </li>

          <li class="nav-item nav-dropdown">
            <a class="nav-link nav-dropdown-toggle" href="#"><i class="fa fa-user"></i> Users</a>
            <ul class="nav-dropdown-items">
              <li class="nav-item">
                <a class="nav-link" href=""><i class="fa fa-user ml-2"></i> All Users</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href=""><i class="fas fa-user-plus ml-2"></i> Create User</a>
              </li>
            </ul>
          </li>

          <li class="nav-item nav-dropdown">
            <a class="nav-link nav-dropdown-toggle" href="#"><i class="fa fa-envelope"></i> Message</a>
            <ul class="nav-dropdown-items">
              <li class="nav-item">
                <a class="nav-link" href=""><i class="fa fa-comment ml-2"></i> Meetings</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href=""><i class="fa fa-user ml-2"></i> Inbox</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href=""><i class="fas fa-comment-alt ml-2"></i> Message to all</a>
              </li>
            </ul>
          </li>

          <li class="divider"></li>
          <li class="nav-title">
            Extras
          </li>
          <li class="nav-item nav-dropdown">
            <a class="nav-link nav-dropdown-toggle" href="#"><i class="fa fa-star"></i> Pages</a>
            <ul class="nav-dropdown-items">
              {% if user.is_authenticated %}
              <!-- <li class="nav-item">
                <a class="nav-link" href="{% url 'core:login' %}" target="_top"><i class="fa fa-sign-in"></i> Login</a>
              </li> -->
              <li class="nav-item">
                <a class="nav-link" href="{% url 'core:logout' %}" target="_top"><i class="fa fa-sign-out"></i> Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'core:login' %}" target="_top"><i class="fa fa-sign-in"></i> Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'core:logout' %}" target="_top"><i class="fa fa-sign-out"></i> Logout</a>
              </li>
              {% endif %}
            </ul>
          </li>
        </ul>
      </nav>
      <button class="sidebar-minimizer brand-minimizer" type="button"></button>
    </div>

    <!-- Main content -->
    <main class="main">
      <!-- Breadcrumb -->
      <ol class="breadcrumb">
        {% block breadcrumb %}
        <li class="breadcrumb-item active">Home</li>
        <li class="breadcrumb-item">Dashboard</li>
        {% endblock breadcrumb%}

        <!-- Breadcrumb Menu-->
        <li class="breadcrumb-menu d-md-down-none">
          <div class="btn-group" role="group" aria-label="Button group">
            <a class="btn" href="{% url 'core:dashboard' %}"><i class="fa fa-tachometer-alt"></i> &nbsp;Dashboard</a>
          </div>
        </li>
      </ol>
{% block content %}
{% endblock %}
    </main>


  </div>

  <footer class="app-footer">
    <span>Copyright © 2022 | Virtual Office Room</span>
  </footer>

  <script>
    // Get the modal
    var modal = document.getElementById("myModal");
    
    // Get the button that opens the modal
    {% comment %} var btn = document.getElementById("myBtn"); {% endcomment %}
    
    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    var d = new Date();
    var time = d.getHours();

    console.log(time)

    if (time < 12 ) {
      modal.style.display = "block";
    }
    if (time > 12) {
      document.write("<b>Good afternoon!</b>");
    }
    if (time == 12) {
      document.write("<b>Go eat lunch!</b>");
    }
    
    // When the user clicks the button, open the modal 
    {% comment %} btn.onclick = function() {
      modal.style.display = "block";
    } {% endcomment %}
    
    // When the user clicks on <span> (x), close the modal
    span.onclick = function() {
      modal.style.display = "none";
    }
    
    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
      if (event.target == modal) {
        modal.style.display = "none";
      }
    }
    </script>

  <!-- Bootstrap and necessary plugins -->
    <script src="{% static 'vendors/js/jquery.min.js'%}"></script>
    <script src="{% static 'vendors/js/popper.min.js'%}"></script>
    <script src="{% static 'vendors/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'vendors/js/pace.min.js'%}"></script>
    <script src="{% static 'vendors/js/Chart.min.js'%}"></script>

  <!-- CoreUI main scripts -->

    <script src="{% static 'js/app.js'%}"></script>

  <!-- Plugins and scripts required by this views -->

  <!-- Custom scripts required by this view -->
    <script src="{% static 'js/main.js'%}"></script>

</body>
{% endblock body %}
</html>

core/templates/core/dashboard.html
{% extends 'core/base.html' %}
{% load static %}

{% block title%} Dashboard {% endblock %}
{% block content %}

<div class="container-fluid">
<div class="animated fadeIn">
  <div class="row">
    <!--/.col-->

    <div class="col-sm-12 col-lg-6">
      <div class="card text-white bg-info">
        <div class="card-body pb-0">
          <!-- <button type="button" class="btn btn-transparent p-0 float-right">
            <i class="fa fa-cog"></i>
          </button> -->
          <h4 class="mb-0">{{ users.count }}</h4>
          <p>Registered Users</p>
        </div>
        <div class="chart-wrapper px-3" style="height:70px;"><div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
          <canvas id="card-chart1" class="chart chartjs-render-monitor" height="70" width="248" style="display: block; width: 248px; height: 70px;"></canvas>
        </div>
      </div>
    </div>
    <!--/.col-->

    <div class="col-sm-12 col-lg-6">
      <div class="card text-white bg-info">
        <div class="card-body pb-0">
          <div class="btn-group float-right">
            <!-- <button type="button" class="btn btn-transparent dropdown-toggle p-0" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-cog"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div> -->
          </div>
          <h4 class="mb-0">{{ project }}</h4>
          <p>Projects</p>
        </div>
        <div class="chart-wrapper" style="height:70px;"><div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
          <canvas id="card-chart2" class="chart chartjs-render-monitor" height="70" width="280" style="display: block; width: 280px; height: 70px;"></canvas>
        </div>
      </div>
    </div>
    <!--/.col-->

    <div class="col-sm-12 col-lg-6">
      <div class="card text-white bg-warning">
        <div class="card-body pb-0">
          <div class="btn-group float-right">
            <!-- <button type="button" class="btn btn-transparent dropdown-toggle p-0" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-cog"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div> -->
          </div>
          <h4 class="mb-0">{{ active_proeject }}</h4>
          <p>Active Projects</p>
        </div>
        <div class="chart-wrapper" style="height:70px;"><div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
          <canvas id="card-chart3" class="chart chartjs-render-monitor" height="70" width="280" style="display: block; width: 280px; height: 70px;"></canvas>
        </div>
      </div>
    </div>
    <!--/.col-->

    <div class="col-sm-12 col-lg-6">
      <div class="card text-white bg-danger">
        <div class="card-body pb-0">
          <div class="btn-group float-right">
            <!-- <button type="button" class="btn btn-transparent dropdown-toggle p-0" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> -->
              <!-- <i class="fa fa-cog"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div> -->
          </div>
          <h4 class="mb-0">{{ task }}</h4>
          <p>Tasks</p>
        </div>
        <div class="chart-wrapper px-3" style="height:70px;"><div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
          <canvas id="card-chart4" class="chart chartjs-render-monitor" height="70" width="248" style="display: block; width: 248px; height: 70px;"></canvas>
        </div>
      </div>
    </div>
    <!--/.col-->
  </div>
  <!--/.row-->
</div>

</div>

{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}
{% block breadcrumb %}
<li class="breadcrumb-item active">Home</li>
{% endblock breadcrumb%}

{% block content %}
<div class="container-fluid">
  <div id="ui-view" style="opacity: 1;"><div class="animated fadeIn">
    <div class="row">
    <div class="col-12">
      <div class="card">
      <div class="card-header">
        <i class="fa fa-align-justify"></i> Main info
        <div class="card-actions">
          {% comment %} <a href="" target="_blank">
            <small class="text-muted">docs</small>
          </a> {% endcomment %}
        </div>
      </div>
      <div class="card-body">
        <div class="jumbotron bg-white">
          <h1 class="display-4">Virtual Office Room</h1>
          <p class="lead">Welcome to the Virtual Office Room.</p>
          <hr class="my-4">
          <p>Register yourself and start managing your projects</p>
          <p>Projects which are assigned to you only will be displayed, also with given task</p>
          <p class="lead">
            <a class="btn btn-primary btn-lg" href="{% url 'user:register' %}" role="button">Register Yourself</a>
          </p>
          {% if not user.is_authenticated %}
          <a href="{% url 'core:login' %}">Click here if you are already registered</a>
          {% endif %}
        </div>
      </div>
      </div>
    </div>
    </div>
    </div>
  </div>
</div>

{% endblock %}